VALID_RR_INFO = [
    {
        "Type": "A",
        "Type id (decimal)": "1",
        "Defining RFC": "RFC 1035[1]",
        "Description": "IPv4 Address record",
        "Function": "Returns a 32-bit IPv4 address, most commonly used to map hostnames to an IP address of the host, but it is also used for DNSBLs, storing subnet masks in RFC 1101, etc.",
    },
    {
        "Type": "AAAA",
        "Type id (decimal)": "28",
        "Defining RFC": "RFC 3596[2]",
        "Description": "IPv6 address record",
        "Function": "Returns a 128-bit IPv6 address, most commonly used to map hostnames to an IP address of the host.",
    },
    {
        "Type": "AFSDB",
        "Type id (decimal)": "18",
        "Defining RFC": "RFC 1183",
        "Description": "AFS database record",
        "Function": "Location of database servers of an AFS cell. This record is commonly used by AFS clients to contact AFS cells outside their local domain. A subtype of this record is used by the obsolete DCE/DFS file system.",
    },
    {
        "Type": "APL",
        "Type id (decimal)": "42",
        "Defining RFC": "RFC 3123",
        "Description": "Address Prefix List",
        "Function": "Specify lists of address ranges, e.g. in CIDR format, for various address families. Experimental.",
    },
    {
        "Type": "CAA",
        "Type id (decimal)": "257",
        "Defining RFC": "RFC\u00a06844",
        "Description": "Certification Authority Authorization",
        "Function": "DNS Certification Authority Authorization, constraining acceptable CAs for a host/domain",
    },
    {
        "Type": "CDNSKEY",
        "Type id (decimal)": "60",
        "Defining RFC": "RFC 7344",
        "Description": "",
        "Function": "Child copy of DNSKEY record, for transfer to parent",
    },
    {
        "Type": "CDS",
        "Type id (decimal)": "59",
        "Defining RFC": "RFC 7344",
        "Description": "Child DS",
        "Function": "Child copy of DS record, for transfer to parent",
    },
    {
        "Type": "CERT",
        "Type id (decimal)": "37",
        "Defining RFC": "RFC 4398",
        "Description": "Certificate record",
        "Function": "Stores PKIX, SPKI, PGP, etc.",
    },
    {
        "Type": "CNAME",
        "Type id (decimal)": "5",
        "Defining RFC": "RFC 1035[1]",
        "Description": "Canonical name record",
        "Function": "Alias of one name to another: the DNS lookup will continue by retrying the lookup with the new name.",
    },
    {
        "Type": "CSYNC",
        "Type id (decimal)": "62",
        "Defining RFC": "RFC 7477",
        "Description": "Child-to-Parent Synchronization",
        "Function": "Specify a synchronization mechanism between a child and a parent DNS zone. Typical example is declaring the same NS records in the parent and the child zone",
    },
    {
        "Type": "DHCID",
        "Type id (decimal)": "49",
        "Defining RFC": "RFC 4701",
        "Description": "DHCP identifier",
        "Function": "Used in conjunction with the FQDN option to DHCP",
    },
    {
        "Type": "DLV",
        "Type id (decimal)": "32769",
        "Defining RFC": "RFC 4431",
        "Description": "DNSSEC Lookaside Validation record",
        "Function": "For publishing DNSSEC trust anchors outside of the DNS delegation chain.  Uses the same format as the DS record. RFC 5074 describes a way of using these records.",
    },
    {
        "Type": "DNAME",
        "Type id (decimal)": "39",
        "Defining RFC": "RFC 6672",
        "Description": "Delegation name record",
        "Function": "Alias for a name and all its subnames, unlike CNAME, which is an alias for only the exact name. Like a CNAME record, the DNS lookup will continue by retrying the lookup with the new name.",
    },
    {
        "Type": "DNSKEY",
        "Type id (decimal)": "48",
        "Defining RFC": "RFC 4034",
        "Description": "DNS Key record",
        "Function": "The key record used in DNSSEC. Uses the same format as the KEY record.",
    },
    {
        "Type": "DS",
        "Type id (decimal)": "43",
        "Defining RFC": "RFC 4034",
        "Description": "Delegation signer",
        "Function": "The record used to identify the DNSSEC signing key of a delegated zone",
    },
    {
        "Type": "EUI48",
        "Type id (decimal)": "108",
        "Defining RFC": "RFC 7043",
        "Description": "MAC address (EUI-48)",
        "Function": "A 48-bit IEEE Extended Unique Identifier.",
    },
    {
        "Type": "EUI64",
        "Type id (decimal)": "109",
        "Defining RFC": "RFC 7043",
        "Description": "MAC address (EUI-64)",
        "Function": "A 64-bit IEEE Extended Unique Identifier.",
    },
    {
        "Type": "HINFO",
        "Type id (decimal)": "13",
        "Defining RFC": "RFC 8482",
        "Description": "Host Information",
        "Function": "Providing Minimal-Sized Responses to DNS Queries That Have QTYPE=ANY",
    },
    {
        "Type": "HIP",
        "Type id (decimal)": "55",
        "Defining RFC": "RFC 8005",
        "Description": "Host Identity Protocol",
        "Function": "Method of separating the end-point identifier and locator roles of IP addresses.",
    },
    {
        "Type": "HTTPS",
        "Type id (decimal)": "65",
        "Defining RFC": "RFC 9460",
        "Description": "HTTPS Binding",
        "Function": "RR that improves performance for clients that need to resolve many resources to access a domain.",
    },
    {
        "Type": "IPSECKEY",
        "Type id (decimal)": "45",
        "Defining RFC": "RFC 4025",
        "Description": "IPsec Key",
        "Function": "Key record that can be used with IPsec",
    },
    {
        "Type": "KEY",
        "Type id (decimal)": "25",
        "Defining RFC": "RFC 2535[3] and RFC 2930[4]",
        "Description": "Key record",
        "Function": "Used only for SIG(0) (RFC 2931) and TKEY (RFC 2930).[5] RFC 3445 eliminated their use for application keys and limited their use to DNSSEC.[6] RFC 3755 designates DNSKEY as the replacement within DNSSEC.[7] RFC 4025 designates IPSECKEY as the replacement for use with IPsec.[8]",
    },
    {
        "Type": "KX",
        "Type id (decimal)": "36",
        "Defining RFC": "RFC 2230",
        "Description": "Key Exchanger record",
        "Function": "Used with some cryptographic systems (not including DNSSEC) to identify a key management agent for the associated domain-name.  Note that this has nothing to do with DNS Security.  It is Informational status, rather than being on the IETF standards-track.  It has always had limited deployment, but is still in use.",
    },
    {
        "Type": "LOC",
        "Type id (decimal)": "29",
        "Defining RFC": "RFC 1876",
        "Description": "Location record",
        "Function": "Specifies a geographical location associated with a domain name",
    },
    {
        "Type": "MX",
        "Type id (decimal)": "15",
        "Defining RFC": "RFC 1035[1] and RFC 7505",
        "Description": "Mail exchange record",
        "Function": "List of mail exchange servers that accept email for a domain",
    },
    {
        "Type": "NAPTR",
        "Type id (decimal)": "35",
        "Defining RFC": "RFC 3403",
        "Description": "Naming Authority Pointer",
        "Function": "Allows regular-expression-based rewriting of domain names which can then be used as URIs, further domain names to lookups, etc.",
    },
    {
        "Type": "NS",
        "Type id (decimal)": "2",
        "Defining RFC": "RFC 1035[1]",
        "Description": "Name server record",
        "Function": "Delegates a DNS zone to use the given authoritative name servers",
    },
    {
        "Type": "NSEC",
        "Type id (decimal)": "47",
        "Defining RFC": "RFC 4034",
        "Description": "Next Secure record",
        "Function": "Part of DNSSEC\u2014used to prove a name does not exist. Uses the same format as the (obsolete) NXT record.",
    },
    {
        "Type": "NSEC3",
        "Type id (decimal)": "50",
        "Defining RFC": "RFC 5155",
        "Description": "Next Secure record version 3",
        "Function": "An extension to DNSSEC that allows proof of nonexistence for a name without permitting zonewalking",
    },
    {
        "Type": "NSEC3PARAM",
        "Type id (decimal)": "51",
        "Defining RFC": "RFC 5155",
        "Description": "NSEC3 parameters",
        "Function": "Parameter record for use with NSEC3",
    },
    {
        "Type": "OPENPGPKEY",
        "Type id (decimal)": "61",
        "Defining RFC": "RFC 7929",
        "Description": "OpenPGP public key record",
        "Function": "A DNS-based Authentication of Named Entities (DANE) method for publishing and locating OpenPGP public keys in DNS for a specific email address using an OPENPGPKEY DNS resource record.",
    },
    {
        "Type": "PTR",
        "Type id (decimal)": "12",
        "Defining RFC": "RFC 1035[1]",
        "Description": "PTR Resource Record\u00a0[de]",
        "Function": "Pointer to a canonical name. Unlike a CNAME, DNS processing stops and just the name is returned.  The most common use is for implementing reverse DNS lookups, but other uses include such things as DNS-SD.",
    },
    {
        "Type": "RRSIG",
        "Type id (decimal)": "46",
        "Defining RFC": "RFC 4034",
        "Description": "DNSSEC signature",
        "Function": "Signature for a DNSSEC-secured record set. Uses the same format as the SIG record.",
    },
    {
        "Type": "RP",
        "Type id (decimal)": "17",
        "Defining RFC": "RFC 1183",
        "Description": "Responsible Person",
        "Function": "Information about the responsible person(s) for the domain. Usually an email address with the @ replaced by a .",
    },
    {
        "Type": "SIG",
        "Type id (decimal)": "24",
        "Defining RFC": "RFC 2535",
        "Description": "Signature",
        "Function": "Signature record used in SIG(0) (RFC 2931) and TKEY (RFC 2930).[7] RFC 3755 designated RRSIG as the replacement for SIG for use within DNSSEC.[7]",
    },
    {
        "Type": "SMIMEA",
        "Type id (decimal)": "53",
        "Defining RFC": "RFC 8162[9]",
        "Description": "S/MIME cert association[10]",
        "Function": "Associates an S/MIME certificate with a domain name for sender authentication.",
    },
    {
        "Type": "SOA",
        "Type id (decimal)": "6",
        "Defining RFC": "RFC 1035[1] and RFC 2308[11]",
        "Description": "Start of [a zone of] authority record",
        "Function": "Specifies authoritative information about a DNS zone, including the primary name server, the email of the domain administrator, the domain serial number, and several timers relating to refreshing the zone.",
    },
    {
        "Type": "SRV",
        "Type id (decimal)": "33",
        "Defining RFC": "RFC 2782",
        "Description": "Service locator",
        "Function": "Generalized service location record, used for newer protocols instead of creating protocol-specific records such as MX.",
    },
    {
        "Type": "SSHFP",
        "Type id (decimal)": "44",
        "Defining RFC": "RFC 4255",
        "Description": "SSH Public Key Fingerprint",
        "Function": "Resource record for publishing SSH public host key fingerprints in the DNS, in order to aid in verifying the authenticity of the host. RFC 6594 defines ECC SSH keys and SHA-256 hashes. See the IANA SSHFP RR parameters registry for details.",
    },
    {
        "Type": "SVCB",
        "Type id (decimal)": "64",
        "Defining RFC": "RFC 9460",
        "Description": "Service Binding",
        "Function": "RR that improves performance for clients that need to resolve many resources to access a domain.",
    },
    {
        "Type": "TA",
        "Type id (decimal)": "32768",
        "Defining RFC": "\u2014",
        "Description": "DNSSEC Trust Authorities",
        "Function": "Part of a deployment proposal for DNSSEC without a signed DNS root. See the IANA database and Weiler Spec for details.   Uses the same format as the DS record.",
    },
    {
        "Type": "TKEY",
        "Type id (decimal)": "249",
        "Defining RFC": "RFC 2930",
        "Description": "Transaction Key record",
        "Function": "A method of providing keying material to be used with TSIG that is encrypted under the public key in an accompanying KEY RR.[12]",
    },
    {
        "Type": "TLSA",
        "Type id (decimal)": "52",
        "Defining RFC": "RFC 6698",
        "Description": "TLSA certificate association",
        "Function": "A record for DANE. RFC 6698 defines \"The TLSA DNS resource record is used to associate a TLS server certificate or public key with the domain name where the record is found, thus forming a 'TLSA certificate association'\".",
    },
    {
        "Type": "TSIG",
        "Type id (decimal)": "250",
        "Defining RFC": "RFC 2845",
        "Description": "Transaction Signature",
        "Function": "Can be used to authenticate dynamic updates as coming from an approved client, or to authenticate responses as coming from an approved recursive name server[13] similar to DNSSEC.",
    },
    {
        "Type": "TXT",
        "Type id (decimal)": "16",
        "Defining RFC": "RFC 1035[1]",
        "Description": "Text record",
        "Function": "Originally for arbitrary human-readable text in a DNS record. Since the early 1990s, however, this record more often carries machine-readable data, such as specified by RFC 1464, opportunistic encryption, Sender Policy Framework, DKIM, DMARC, DNS-SD, etc.",
    },
    {
        "Type": "URI",
        "Type id (decimal)": "256",
        "Defining RFC": "RFC 7553",
        "Description": "Uniform Resource Identifier",
        "Function": "Can be used for publishing mappings from hostnames to URIs.",
    },
    {
        "Type": "ZONEMD",
        "Type id (decimal)": "63",
        "Defining RFC": "RFC 8976",
        "Description": "Message Digests for DNS Zones",
        "Function": "Provides a cryptographic message digest over DNS zone data at rest.",
    },
]


def compile_rr_data():
    compiled = {}
    for i, rr in enumerate(VALID_RR_INFO):
        if "IPv4" in rr["Description"]:
            compiled[rr["Type"]] = "IPv4"
        elif "IPv6" in rr["Description"]:
            compiled[rr["Type"]] = "IPv6"
